app:
  addr: ":8080"
  token_key: uN8tUgn8hzN6ftVrKyK6OxJj2kaQ5JcX

mongo:
  uri: mongodb://127.0.0.1:27017
  database: lim

redis:
  addr: 127.0.0.1:6379
  pass: ''

oss:
  type: minio
  minio:
    endpoint: 127.0.0.1:9000
    tls: False
    bucket: lim
    access_key_id: 'root'
    secret_access_key: '12345678'
    token: ''
